### ISSUE TITLE
onnx import problem with pytorch Linear

### ISSUE THREAD

**Issue by gdm01** [sony/nnabla#381]
Hi,
If I try to use nnabla_cli to convert a simple ONNX file exported from Pytorch it fails with the following error:
ValueError: Unsupported attribute alpha was specified at Gemm

This seems to be caused by torch.nn.Linear() exporting with alpha (1.0) which seems correct for ONNX but unsupported by the nnabla_cli converter?

Is there a workaround for this?

**Comment by TomonobuTsujikawa** [comment]
Hi, We're sorry to late response.
This issue is fixed by https://github.com/sony/nnabla/commit/e87b689c51573fbc04abbba379337940c38649e9, and released as v1.0.18.
The file format convert is improved day by day. So, please check the latest status from here:
https://nnabla.readthedocs.io/en/latest/python/file_format_converter/Function-Level_Support_Status.html

**Comment by TomonobuTsujikawa** [comment]
We close this issue.
Please let us know if your issue still exist.
